config/routes.rb
Rails.application.routes.draw do

  root 'welcomes#index'
  resources :albums
  resources :artists
  resources :users
  resources :rspotifys
  resources :songs
  resources :tweets

  get '/login' => 'sessions#new'
  post '/sessions' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

end

app/models/album.rb
class Album < ActiveRecord::Base

  belongs_to :artist  

  has_many :songs
end

app/models/artist.rb
class Artist < ActiveRecord::Base

  has_many :albums,:dependent => :nullify
  has_many :songs
  has_many :toptracks

end

app/models/singer.rb
class Actor < ActiveRecord::Base

  has_many :albums
  has_many :songs

end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :artist
  belongs_to :album
end

app/models/toptrack.rb
class Toptrack < ActiveRecord::Base
  belongs_to :artist
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :tweets
	has_secure_password
	mount_uploader :image, ImageUploader
	validates_processing_of :image
	validate :image_size_validation
	 
	private
	  def image_size_validation
	    errors[:image] << "should be less than 500KB" if image.size > 0.5.megabytes
	  end

	GENDER_TYPES = ["Not telling","Male", "Female"]
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
skip_before_filter :verify_authenticity_token, :only => :create
	def index
		@albums = Album.all
		
		if params[:keyword].present?
     	 @albums = @albums.where("title LIKE ? OR year = ?",
                                             "%#{params[:keyword]}%", params[:keyword])
    	end
		@albums = @albums.limit(100)
		@albums = @albums.shuffle
	end

	def show
		@album = Album.find_by(id: params[:id])
  	end

	def new
		redirect_to rspotifys_url
	end

	def create
		if Album.find_by(spotify_id:params[:spotifyid]) == nil
			@album = Album.new
		    @album.title = params[:title]
		    @album.image_url = params[:image_url]
		    @album.year = params[:year]
		    @album.popularity = params[:popularity]
		    @album.total_tracks = params[:total_tracks]
		    @album.album_type = params[:album_type]
		    @album.spotify_id = params[:spotifyid]
		    artist = Artist.find_by(spotify_id: params[:artist_sid])
		    if artist==nil
		    	spotifyartist = RSpotify::Artist.find(params[:artist_sid])
		    	artist = Artist.create(name:params[:artist],spotify_id:spotifyartist.id,photo_url: spotifyartist.images[1]['url'])
		    	spotifyartist.top_tracks('us').each do |top|
		    		Toptrack.create(name:top.name, preview_url:top.preview_url, artist_id:artist.id)
		    	end
		    end
				@album.artist_id = artist.id

		    if @album.save
		    	mtracks = RSpotify::Album.find(params[:spotifyid])
		    	mtracks.tracks.each do |song|
		    		@newsong = Song.new(name: song.name, runtime:song.duration_ms, album_id: @album.id, artist_id: artist.id, preview_url: song.preview_url,popularity: song.popularity)
		    		@newsong.save
		   		end


		      redirect_to albums_url, notice: "Album added! Thanks!"
		    else
		      render 'new'
		    end

		else
			flash[:warning] = "Album already exsists!"
			redirect_to albums_url
		end

	end

	def edit

	end

	def update

	end

	def destroy
		Album.delete(params[:id])
    	redirect_to albums_url
	end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  def index

     @artists = Artist.order('id ASC').reorder('name ASC')
     if params[:keyword].present?
       @artists = @artists.where("name LIKE ?","%#{params[:keyword]}%")
     end
     @artists = @artists.limit(50)
  end

  def show
     @artist = Artist.find_by(id: params[:id])
  end

  def destroy
    artist = Artist.find_by(id:params[:id])
    if artist
       albums = Album.where(artist_id:artist.id)
       albums.each do |album|
        album.delete
       end
      songs = Song.where(artist_id:artist.id)
      songs.each do |song|
        song.delete
      end
      artist.delete
    end
    redirect_to albums_url notice: '#{artist.name} was successfully deleted'
  end
  
end

app/controllers/rspotifys_controller.rb
class RspotifysController < ApplicationController
	def show
		@album = RSpotify::Album.find(params[:id])
  	end

	def index
     	if params[:album_name]!=nil and params[:album_name].length>0
     		@album = RSpotify::Album.search(params[:album_name])
     	end
	end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(email: params[:email])
    if user
      if user.authenticate(params[:password])
        session["user_id"] = user.id
        flash[:success] = "Welcome back, #{user.name}"
        redirect_to albums_url
        return
      else
      end
    else
    end
    flash[:danger] = "Invalid email or password"
    redirect_to login_url
  end

  def destroy
    reset_session
    redirect_to root_path
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def show
     @song = Song.find_by(id: params[:id])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]
  def new
  end
  def create
    @tweet = Tweet.new(content:params[:tweet][:content],user_id:params[:tweet][:user_id])
    @tweet.time = Time.now.strftime("%Y-%m-%d %H:%M:%S")
    @tweet.save   
  end

  def destroy
    user = User.find_by(id:@tweet.user_id)
    @tweet.destroy
    redirect_to user_url(user) ,notice: 'tweet was successfully deleted'
  end

  private
  def set_tweet
      @tweet = Tweet.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def show
    if !@user || (@user.id != session[:user_id].to_i)
      redirect_to root_url
    end
  end

  def new
    @user = User.new
  end

  def index
    @users = User.all
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def create
    if User.find_by(email:params[:user][:email])!=nil
      flash[:danger]="Email already exists"
        redirect_to new_user_url
    else
      if params[:user][:password] == params[:user][:password_confirmation]
        user = User.new
        user.name = params[:user][:name]
        user.email = params[:user][:email]
        user.password = params[:user][:password]
        user.image = "male_default.png"
        if user.save
          flash[:success] = "User was successfully created."
          redirect_to login_url
        else
          flash[:danger] = "Somgthing went wrong"
          redirect_to new_user_url
        end
      else
        flash[:danger]="Password not match"
        redirect_to new_user_url
      end
    end
  end

  def destroy
    @user.destroy
    redirect_to albums_url, notice: 'User was successfully deleted'
  end

  private
  def set_user
      @user = User.find(params[:id])
  end
  def user_params
      params.require(:user).permit(:name,:image, :gender, :birthday, :email)
  end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/_album.html.erb
  <% poster_url = album ? album.image_url : 'add_new.png' %>
<% path = album ? album_path(album.id) : new_album_path %>

<div class="album-box">
<ul>
<%= link_to image_tag(poster_url), path%>
  <% if album %>
    <h4><%= link_to album.title, album_path(album.id) %></h4>
  <% end %>
</ul>
</div>

app/views/albums/_details.html.erb
<div class="container-fluid">
  <div class="row">


<div class="col-xs-12 col-sm-10 col-md-8 col-lg-8">
  <p><strong><span class="label label-info">Artist:</span></strong>
    <%= link_to @album.artist.name, artist_path(@album.artist.id) %>
  </p>

  <p><strong><span class="label label-info">Released:</span></strong> <%= @album.year %></p>

  <p><strong><span class="label label-info">Popularity:</span></strong> <%= @album.popularity%></p>
  <p><strong><span class="label label-info">Type:</span></strong> <%= @album.album_type%></p>
  <p><strong><span class="label label-info">total_tracks:</span></strong> <%= @album.total_tracks%></p>
  <p><strong><span class="label label-info">Tracks:</span></strong></p>
  <hr>
  <ul>
    <% @album.songs.each do |song| %>
        <li class="track-list"><%= link_to song.name, song_path(song.id) %></li>
    <% end %>
  </ul>
  </div>
  <div class="col-sm-2 col-md-4 col-lg-4">
  <p><%= image_tag @album.image_url%></p>

  </div>
</div>
</div>
<hr>

app/views/albums/index.html.erb
<div class="page-header text-center"><h1>ALBUM</h1></div>
<% if session["user_id"].present? and User.find_by(id: session["user_id"])!=nil%>
 <%= render 'album', album: nil %>
 <%end%>
<%= render @albums %>
<%if @albums.count > 0%>
<div class="album-box-noshadow">
<ul>
<%= link_to image_tag("pick.jpg"), album_url(@albums.sample)%>
</ul>
</div>
<%end%>

app/views/albums/show.html.erb
<h1 class='page-header'><%= @album.title%></h1>

<%= render 'details' %>

 <% if session["user_id"].present? and User.find_by(id: session["user_id"])!=nil%>
 <div class="text-center">
    <%=button_to "Delete",album_path(@album.id),:method => :delete, :class=>"btn btn-sm btn-danger"%>
  </div>
  <%end%>

app/views/artists/_details.html.erb
<script>
  var player = document.createElement('AUDIO');
  var isPlaying = false;
</script>

<h1 class='page-header'><%=@artist.name %>
</h1>
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12 col-sm-4 col-md-3 col-lg-3 sidebar">
      <p><%= image_tag @artist.photo_url, class: 'img-circle artist-photo' %></p> 
      <h3 class = "text-center"> <span class="label label-warning">
      Top 10 Tracks
      </span>
      </h3>
      <hr>
      <%tracks = @artist.toptracks.all%>
      <ul>
        <%tracks.each do |track|%>
          <li class="track-list">
            <a hr="#" class="audioplay au-<%= track.id %>" data-audiofile="<%=track.preview_url%>"> 
            <%= track.name %>
            </a>
          </li>
        <%end%>
      </ul>
       <% if session["user_id"].present? and User.find_by(id: session["user_id"])!=nil%>
      <div class = "text-center">
      <%=button_to "Delete",artist_path(@artist.id),:method => :delete, :class=>"btn btn-sm btn-danger"%>
      </div>
      <%end%>
      <hr>
    </div>
    <div class="col-xs-0 col-sm-8 col-md-9 col-lg-9">
      <% albums = Album.where(artist_id: @artist.id) %>
      <% albums.each do |album| %>
        <div class='artist-box'>
          <%= link_to image_tag(album.image_url), album_path(album.id) %>
          <h4><%= link_to album.title, album_path(album.id) %></h4>
        </div>
      <% end %>
    </div>
  </div>
</div>

<script>
  $(".audioplay").on("click", function(){
     var source = $(this).data("audiofile");
     if(player.src == source && isPlaying)
     {
      player.pause();
      isPlaying = false;
     }
     else
     {
      player.src = source
      player.play();
      isPlaying = true;
     }
     
  });
</script>

app/views/artists/index.html.erb
<br>
<h1>Artists</h1>

<% @artists.each do |artist| %>
	<hr>
  <div class='tweet-box'>
  <%= link_to image_tag(artist.photo_url), artist_path(artist.id)%>
<strong><span class="label label-success"><%= link_to artist.name, artist_path(artist.id) , style:"color:#ffffff"%></span></strong>
  	</div>
  	
<% end %>

app/views/artists/show.html.erb
<%=render 'details'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Final</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
   <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
        <div class = "container">
          <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Listen</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li><%= link_to "Albums", albums_path %></li>
              <li><%= link_to "Artists", artists_path %></li>
              <li><%= link_to "Community", users_path %></li>
              <li><%= link_to "Spotify", rspotifys_path %></li>
            </ul>
             <% if session["user_id"].present? and User.find_by(id: session["user_id"])!=nil%>
            <div class="navbar-form navbar-left" role="search">
          <div class="form-group" >
           <%= form_tag albums_url, :method => :get do %>
           <%= text_field_tag :keyword, '', placeholder: 'Search',:class => "form-control" ,:style=>"width:150px;"%>
        </div>
           <%end%>
            </div>
            <%end%>

            <ul class="nav navbar-nav navbar-right">
              <% if session["user_id"].present? and User.find_by(id: session["user_id"])!=nil%>
              <% current_user = User.find_by(id: session["user_id"]) %>
              <li class="dropdown theme-dropdown clearfix">
               <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%=current_user.name%> <span class="caret"></span></a>
              <ul class="dropdown-menu" aria-labelledby="dropdownMenuDivider ">
                <li><%= link_to "My Account", user_path(current_user) %></li>
                <li role="separator" class="divider"> </li>
                  <li><%= link_to "Sign Out", logout_path %></li>
              </ul>
              </li>
              <% else %>
                <li><%= link_to "Sign Up", new_user_path %></li>
                <li><%= link_to "Sign In", login_path %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
          </div>
        </div><!--/.container-fluid -->
      </nav>


<div class="container">

<% flash.each do |key, value| %>

  <%if key=='notice'%>
  <div class="alert alert-success"><%= value %></div>
  <%else%>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <%end%>
  
<% end %>

<%= yield %>
</div>


<br>
<br>
<hr>
<footer class="footer">
      <div class="container">
        <p class="text-muted text-center">Tianyu Song All Rights Reserved.</p>
      </div>
    </footer>
</body>

</html>

app/views/rspotify/index.html.erb
<h1>Add a New Album</h1>


<%= form_tag '/spotify/new', method: "get", html: { class: "form" } do %>
 <div class="form-group col-xs-4">
   <%= text_field_tag(:album_name, "", placeholder: "Enter album name", class: "form-control") %>
 </div>
 <%= submit_tag "Search on spotify", class: "btn btn-primary" %>
<% end %>

<%if @album!=nil%>
<h2 class="page-header">Albums Matching <%= params[:album_name] %></h2>
<ul>
 <% @album.each do |album| %>
<%= link_to image_tag(album.images[1]['url']), album_path(album.id) %>
 <% end %>
</ul>
<%end%>

app/views/rspotifys/index.html.erb
  <div class = "row">
   <div class="col-md-12">
<h1 class='page-header'>Add a New Album</h1>
</div>
</div>
  <div class = "row">
<%= form_tag '/rspotifys', method: "get", html: { class: "form" } do %>
 <div class="form-group col-sm-4 col-md-4 col-lg-4">
   <%= text_field_tag(:album_name, "", placeholder: "Enter album name", class: "form-control") %>
   </div>
    <div class="col-sm-8 col-md-8 col-lg-8">
 <%= submit_tag "Search on spotify", class: "btn btn-primary" %>
</div>
<% end %>
 </div>
</div>



<%if @album!=nil%>
<ul>
 <% @album.each do |album| %>
 <div class='spotify-box '>
<%= link_to image_tag(album.images[1]['url']), rspotify_path(album.id) %>
<h4><%= link_to album.name, rspotify_path(album.id) %></h4>
</div>
 <% end %>
</ul>

<%end%>

app/views/rspotifys/show.html.erb
<script>
  var player = document.createElement('AUDIO');
  var isPlaying = false;
</script>

<div class="container-fluid">
  <div class="row">
   <div class="col-lg-12">
<h1 class="page-header"><%= @album.name %></h1>
</div>
</div>
<% if session["user_id"].present? and User.find_by(id: session["user_id"])!=nil%>
<div class = "row">
<div class="col-sm-8 col-md-8 col-lg-8">
  <p><strong><span class="label label-info">Artist:</span></strong>
 <%=@album.artists[0].name%>
  </p>

  <p><strong><span class="label label-info">Released:</span> </strong> <%= @album.release_date%></p>
  <p><strong><span class="label label-info">Popularity:</span> </strong> <%= @album.popularity%></p>
  <p><strong><span class="label label-info">Type:</span></strong> <%= @album.album_type%></p>

    
    <p><strong><span class="label label-info">Tracks:</span> </strong><small>(click to play)</small></p>
 <ul>
 <%total_tracks=0%>
   <% @album.tracks.each do |track| %>
     <li class="track-list">
        <a hr="#" class="audioplay au-<%= track.id %>" data-audiofile="<%=track.preview_url%>"> 
      <%= track.name %>
       <%total_tracks=total_tracks+1%>
      </a>
     </li>
   <% end %>
 </ul>
 </div>
  <div class="col-sm-3 col-md-3 col-lg-3">
  <p><%= image_tag @album.images[1]['url']%></p>
</div>
 <hr>
</div>

<div class = "row">
 <div class="col-lg-12">
 <form action="/albums" method="post">
  <input name="title" type="hidden" value= "<%=@album.name%>" />
  <input name="image_url" type="hidden" value= "<%=@album.images[1]['url']%>" />
  <input name="year" type="hidden" value= "<%= @album.release_date%>" />
  <input name="artist" type="hidden" value= "<%= @album.artists[0].name%>" /> 
  <input name="spotifyid" type="hidden" value= "<%= @album.id%>" /> 
  <input name="artist_sid" type="hidden" value= "<%= @album.artists[0].id%>" />
  <input name="popularity" type="hidden" value= "<%= @album.popularity%>" />
  <input name="total_tracks" type="hidden" value= "<%= total_tracks%>" />
  <input name="album_type" type="hidden" value= "<%= @album.album_type%>" />
  <input name="Add This Album" type="submit" value="Add This Album" class="btn btn-success" />
</form>
</div>
</div>

</div>
<%else%>
<div class = "row">
 
<div class="col-sm-8 col-md-8 col-lg-8">
  <p><strong>Artist: </strong>
 <%=@album.artists[0].name%>
  </p>

 <p><strong><span class="label label-info">Released:</span></strong> <%= @album.release_date%></p>
  <p><strong><span class="label label-info">Popularity:</span> </strong> <%= @album.popularity%></p>
  <p><strong><span class="label label-info">Type:</span> </strong> <%= @album.album_type%></p>
 <p><strong><span class="label label-info">Tracks:</span> </strong><small>(login to play)</small></p>
 <ul>
   <% @album.tracks.each do |track| %>
     <li class="track-list">
      <%= track.name %>
     </li>
   <% end %>
 </ul>
 </div>
 <div class="col-sm-3 col-md-3 col-lg-3">
  <p><%= image_tag @album.images[1]['url']%></p>
</div>
 </div>
 <div class = "row">
 <div class="col-lg-12">
    <%=button_to "Log In to Add this album", login_url, :method => :get, :class=>"btn btn-primary"%>
     </div>
     </div>
<%end%>





<script>
  $(".audioplay").on("click", function(){
    
     var source = $(this).data("audiofile");
     if(player.src == source && isPlaying)
     {
      player.pause();
      isPlaying = false;
     }
     else
     {
      player.src = source
      player.play();
      isPlaying = true;
     }
     
  });
</script>

app/views/songs/show.html.erb
<script>
	var player = document.createElement('AUDIO');
	var isPlaying = false;
</script>

<h1 class='page-header'><%= @song.name%></h1>

<%artist = Artist.find_by(id:@song.artist_id)%>
<%album = Album.find_by(id:@song.album_id)%>
<p><strong><span class="label label-info">Artist:</strong></span>
    <%= link_to artist.name, artist_path(@song.artist_id) %>
  </p>
  <p><strong><span class="label label-info">Album:</strong></span>
    <%= link_to album.title, album_path(@song.album_id) %>
  </p>
  <p><strong><span class="label label-info"> Runtime:</span></strong>  <%= @song.runtime/60000%>: <%= (@song.runtime%60000)/1000%> min</p>
  <p><strong><span class="label label-info">Popularity:</span></strong> <%= @song.popularity%></p>
  <hr>

<div class = "text-center">
<button type="button" class="btn btn-lg btn-success" onclick="playAudio()">Play</button>
</div>

<script>
// $(".my_audio").trigger('load');
	function playAudio(){
		if(isPlaying)
		{
			player.pause()
			isPlaying = false;
		}
		else
		{
			player.src = '<%=@song.preview_url%>';
			player.play();
			isPlaying = true;
		}
	}

	window.onbeforeunload = function(){
		if(isPlaying)
		{
			player.pause();
		}
	}

</script>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
      <% @user.errors.full_messages.each do |message| %>
        <div class="alert alert-danger"><%= message %></div>
      <% end %>
      </ul>
  <% end %>


<div class="container-fluid">
  <div class="row">
<div class="col-sm-4 col-md-4 col-lg-4">
<h1> <span class="label label-primary">Update My Infomation</span></h1>
</div>
</div>
<hr>
  <div class = "row">
<div class="col-sm-4 col-md-4 col-lg-4">
<div class="input-group">
  <span class="input-group-addon">
    <%= f.label :name %></span>
    <%= f.text_field :name ,class:"form-control"%>
</div>
  
  <br>
  <div class="input-group">
  <span class="input-group-addon"">
    <%= f.label :birthday %></span>
    <%= f.text_field :birthday,class:"form-control"%>
  </div>
  <br>
   <div class="input-group">
  <span class="input-group-addon"">
  <%= f.label :email %></span>
   <%= f.text_field :email,class:"form-control"%>
   </div>
  <br>
  <div class="input-group">
  <span class="input-group-addon">
     <%= f.label :gender %></span>
   <%= f.select :gender, User::GENDER_TYPES,{}, {class:"form-control"}%> 
</div>
    <%= f.hidden_field :email%>

 </div>
  <div class="col-sm-5 col-md-5 col-lg-5">
  </div>
 <div class="col-sm-3 col-md-3 col-lg-3">
<div class='avatar-box'>
  <div class="field">
    <% if f.object.image? %>
      <%= image_tag f.object.image, class:"img-circle"%>
      <%else %>
        <%if @user.gender == 'Female'%>
          <p><%= image_tag "female_default.png", class:"img-circle"%></p>
        <%else%>
          <p><%= image_tag "male_default.png", class:"img-circle"%></p>
        <%end%>
    <% end %>
    <%= f.label :image, "Avatar" %><br>
    <%= f.file_field :image %>
  </div>
  </div>
  </div>
  </div>
  <hr>
  <div class = "row">
   <div class="col-sm-12 col-md-12 col-lg-12">
   <div class="text-center">
    <%= f.submit "Update",class:"btn btn-default"%>
  </div>
  </div>
  </div>

<% end %>
</div>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<div class="container-fluid">
  <div class="row">
<div class="col-sm-4 col-md-4 col-lg-4">

<h1> <span class="label label-primary">My Account</span>
<small><small><span class="label label-warning">
	 <%= link_to "Edit", edit_user_path(@user.id),style:"color:#ffffff;"%>
</span></small></small>
</h1>
</div>
</div>
<hr>
<div class = "row">
<div class="col-sm-9 col-md-9 col-lg-9">
<% if @user.id == session[:user_id].to_i %>
  <h4><span class="label label-info">Name:</span></h4><h4><%= @user.name %></h4>
  <h4><span class="label label-info">Email:</span></h4><h4><%= @user.email %></h4>
  <h4><span class="label label-info">Birthday:</span></h4><h4><%= @user.birthday %></h4>
  <h4><span class="label label-info">Gender:</span></h4><h4><%= @user.gender %></h4>
  <br>
<% else %>


<% end %>
</div>
<div class="col-sm-3 col-md-3 col-lg-3">
<div class='avatar-box'>

<%if @user.image.length > 0%>
	<p><%= image_tag @user.image, class:"img-circle"%></p>
<%else%>
	<%if @user.gender == 'Female'%>
	<p><%= image_tag "female_default.png", class:"img-circle"%></p>
	<%else%>
	<p><%= image_tag "male_default.png", class:"img-circle"%></p>
	<%end%>
<%end%>
 </div>
</div>
</div>

<div class = "row">
<div class="col-lg-12">
<h3><span class="label label-primary">Tweet</span></h3>
<hr>
<%tweets = @user.tweets.all%>
<%tweets.each do |tweet|%>
<div class = "row">
<div class="col-xs-11 col-sm-11 col-md-11 col-lg-11">
<span class="label label-success"><%=tweet.time%></span>
<%=tweet.content%>
</div>
<div class="col-xs-1 col-sm-1 col-md-1 col-lg-1">
<%=button_to "Delete",tweet_path(tweet.id),:method => :delete, :class=>"btn btn-xs btn-danger"%>

</div>
</div>
<br>
<%end%>
</div>
</div>



<div class = "row">
<div class="col-lg-12">
<hr>
 <div class="text-center">
    <%=button_to "Delete",user_path(@user.id),:method => :delete, :class=>"btn btn-danger"%>
    </div>
    </div>
  </div>
  </div>

app/views/welcomes/index.html.erb
  <body>

    <div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">


          <div class="inner cover">
          
           <h1 class="cover-heading"></h1>
           <br>
           <br>
           <br>
            <h1 class="cover-heading">Listen</h1>
            <p class="lead">"Listen" is a music community where you can collect and play millions of music from the Internet. Join us and invite your friends! Collecting, listening, and sharing your moods!</p>
            <p class="lead">
              <a href="/albums" class="btn btn-lg btn-default">Start</a>
            </p>
          </div>

        </div>

      </div>

    </div>

</body>